version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - FERNET_KEY='jn5cRpx_lMqMvNQm0UtFCMt5KpCrKh33UeNbJS_y1rM='
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CORE_EXECUTOR='LocalExecutor'
            - FERNET_KEY='jn5cRpx_lMqMvNQm0UtFCMt5KpCrKh33UeNbJS_y1rM='
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3